config/routes.rb
Rails.application.routes.draw do
  resources :profiles
	get 'ImDefinitelyRich' => "profiles#new"	
  	get 'Search' => "profiles#index"
  	get 'admin' => "profiles#admin"
  	root 'pages#index'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :myjob, presence: true
  validates :age, presence: true
  validates :source1, presence: true
  validates :net_worth, presence: true
  validates :description, presence: true
  validates :mycountry, presence: true
  validates :mystate, presence: true
  validates_uniqueness_of :first_name, scope: :last_name

  def self.search(search)
	if search
	   where('first_name LIKE :search OR middle_name LIKE :search OR last_name LIKE :search', search: "%#{search}%")
	end
  end
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def welcome
  end 	

  def new
  end	
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    if params[:search]
      @profiles = Profile.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], 
        :per_page => 5 )
    else
      @profiles = Profile.all.order("created_at DESC").paginate(:page => params[:page], 
        :per_page => 5 )
    end 
  end

  def admin
    @profile = Profile.new
    @profiles = Profile.all
  end   

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to admin_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { redirect_to admin_path, notice: 'You didnt put in some important values pls ensure you fix in the important ones, The starred ones must be filled to save or profile is already available' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :middle_name, :last_name, :myjob, :education, :age, :net_worth, 
                     :source1, :source2, :source3, :description, :avatar, :mycountry, :mystate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Famescan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin:0">

<style type="text/css">
html, body {
	height: 100%;
}
</style>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="background-cover-image">
	<div id="canvas" class="background-overlay">
		<div class="nav-bar"><div class="logo bounceInDown animated">FAMESCAN</div></div>
		<div class="main-icons" style="margin-top:20%">
		<a href="/ImDefinitelyRich"><p class="glyphicon glyphicon-plus slideInLeft animated"></p></a>
		<a href="/Search"><p class="glyphicon glyphicon-search slideInRight animated"></p></div></a>

		<div class="guidelines-container">
			<ul class="guidelines slideInLeft animated">
				<li>01. click + to create a profile for yourself</span> </li>
				<li>02. use search icon to find users with their net worth and details </li>
				<li>03. after creating a profile for yourself, shoot us an email of your bank statement|s as proof of networth</li>
				<li>04. your profile with your networth will be visible to everyone that uses this app</li>
				<li>05. voalla you are famous! </li>
			</ul>
		</div>
	</div>
</div>

<script type="text/javascript">
	$("#canvas").particles({
		amount:30,
		duration:{random:true},
		speed:{speed:1},
		layout:"after",
		color:{random:true}
	}).click(function(){
		$(this).particles("stop");
	}).on("stateChange.particles",function(event){
		console.log(event.detail.state);
	});
</script>

app/views/pages/welcome.html.erb
<style type="text/css">
html, body {
	height: 100%;
}
</style>
<div class="col-md-6" style="height:100%">
	<div class="profile-img-container">
		<div class="profile-img"> hello </div>
	</div>
</div>
<div class="col-md-6" style="height:100%">
	<div class="profile-img-container-2">
		<div class="profile-img"> hello </div>
	</div>
</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
<% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

    <ul>
    <% @profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="myfield">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="myfield">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="myfield">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :myjob %><br>
    <%= f.text_field :myjob %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :net_worth %><br>
    <%= f.text_field :net_worth %>
  </div>
  <div class="field">
    <%= f.label "Source of wealth:" %><br>
    <%= f.text_field :source1 %>
    <%= f.text_field :source2 %>
    <%= f.text_field :source3 %>
  </div>
  <div class="field">
    <%= f.label "Brief description about yourself?" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.file_field :avatar %>
  </div>
  <div class="myfield">
    <%= f.label :mycountry %><br>
    <%= f.text_field :mycountry %>
  </div>
  <div class="myfield">
    <%= f.label :mystate %><br>
    <%= f.text_field :mystate %>
  </div>
  <div class="actions field">
    <%= f.submit %>
  </div>
  <% end %>

app/views/profiles/_profile.html.erb
<% @profiles.each do |p| %>
	<%= link_to profile_path(p), class: "box" do %>
	<div class="profile-box">
		<div class="details-box">
			<div class="profile-img" style="background-image: url(<%=p.avatar.url%>);">
			</div>
			<div class="desc-box">
				<div class="profile-name">
					<%= p.first_name %> <%= p.middle_name %> <%=p.last_name%>
				</div>
				<div class="net_worth">
					<%= image_tag "naira.jpg", class: "naira-logo" %> <%= p.net_worth %>
				</div>
				<p class="job"><%= p.job %></p>
			</div>
			<div class="source-container">
				<b style="font-size:10px">Source of wealth?</b>
				<hr style="margin:0">
				<ul>
					<li><%=p.source1%></li>
					<li><%=p.source2%></li>
					<li><%=p.source3%></li>
				</ul>
			</div>
		</div>
	</div>
	<% end %>
<% end %>

app/views/profiles/_sidebar.html.erb
<div class="col-md-2 side-bar-container slideInLeft animated">
	<div class="logo bounceInDown animated">FAMESCAN</div>
</div>

app/views/profiles/admin.html.erb
<div style="padding-left:0" class="col-md-12 admin-container ">
	<%= render "sidebar" %>
	<p id="notice"><%= notice %></p>
	<div class="col-md-6 border">
		<h4>Add Profiles</h4>
			<%= form_for(@profile) do |f| %>
			<div class="myfield">
			<%= f.label :first_name %>*<br>
			<%= f.text_field :first_name %>
			</div>
			<div class="myfield">
			<%= f.label :middle_name %><br>
			<%= f.text_field :middle_name %>
			</div>
			<div class="myfield">
			<%= f.label :last_name %>*<br>
			<%= f.text_field :last_name %>
			</div>
			<div class="field">
			<%= f.label :myjob %>*<br>
			<%= f.text_field :myjob %>
			</div>
			<div class="field">
			<%= f.label :education %><br>
			<%= f.text_field :education %>
			</div>
			<div class="field">
			<%= f.label :age %>*<br>
			<%= f.number_field :age %>
			</div>
			<div class="field">
			<%= f.label :net_worth %>*<br>
			<%= f.text_field :net_worth %>
			</div>
			<div class="field">
			<%= f.label "Source of wealth:" %><br>
			<%= f.text_field :source1 %>*
			<%= f.text_field :source2 %>
			<%= f.text_field :source3 %>
			</div>
			<div class="field">
			<%= f.label "Brief description about yourself?" %>*<br>
			<%= f.text_area :description %>
			</div>
			<div class="field">
			<%= f.file_field :avatar %>
			</div>
			<div class="myfield">
			<%= f.label :mycountry %>*<br>
			<%= f.text_field :mycountry %>
			</div>
			<div class="myfield">
			<%= f.label :mystate %>*<br>
			<%= f.text_field :mystate %>
			</div>
			<div class="actions field">
			<%= f.submit %>
			</div>
			<% end %>
	</div>
	<div class="col-md-4">
		<h4>Profiles saved = <%= @profiles.count %></h4>
		<table class="table">
			<thead>
			<tr>
				<th>Profile name</td>
				<th>Net Worth</td>
				<th colspan="3"></th>	
			</tr>
		    </thead>
			<tbody>
			<% @profiles.each do |p| %>
			<tr>
				<td><%= p.first_name %> <%= p.last_name %></td>
				<td><%= p.net_worth %> </td>
				<td><%= link_to "Open", profile_path(p) %> </td>
				<td><%= link_to "X", profile_path(p), method: :delete, data: {confirm: "Are you sure"} %> </td>
			</tr>
			<% end %>
			<tbody>
		</table>
	</div>
</div>

app/views/profiles/edit.html.erb
<div class="col-sm-4 side-bar-form fadeInLeft animated">
  	<div class="side-bar-overlay">
  		<div class="bounceInDown animated">
  			<a class="logo" href="/">FAMESCAN</a>
  		</div>
  	</div>
</div>
<div class="col-sm-8 zoomInUp animated" style="height:100%; padding-left:100px;">
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>
</div> 

app/views/profiles/index.html.erb
<div class="nav-bar">
  <a href="/"><div class="logo bounceInDown animated float-left">FAMESCAN</div></a>
    <div class="input-container"> 
      <%= form_tag( @profiles_path , method: "get") do %>
        <%= text_field_tag(:search, nil, class: 'input search-icon') %>
      <% end %>
    </div>
</div>

<div class="search-container" style="margin-top:50px">
  <% if @profiles.present? %>
    <%= render 'profile' %>
  <% else %>
    <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class="col-sm-4 side-bar-form fadeInLeft animated">
  	<div class="side-bar-overlay">
  		<div class="bounceInDown animated">
  			<a class="logo" href="/">FAMESCAN</a>
  		</div>
  	</div>
</div>
<div class="col-sm-8 zoomInUp animated" style="height:100%; padding-left:100px;">
	<h1>Lets Get You Up And Running :)</h1>
	<%= render 'form' %>
</div>

app/views/profiles/show.html.erb
<div class="col-sm-4 side-bar fadeInLeft animated" >
  <div class="side-bar-overlay" >
    <div class="bounceInDown animated">
      <a class="logo" href="/">FAMESCAN</a>
    </div>
  </div>
</div>
<div class="col-sm-8 zoomInUp animated" style="height:100%">
  <div class="profile-container">
    <div class="profile-image-container float-left">
      <div class="profile-image" style="background-image: url(<%=@profile.avatar.url%>);"></div>
    </div>  
    <div class="profile-name show-profile-name float-left">
      <%= @profile.first_name %> <%= @profile.middle_name %> <%=@profile.last_name%>
    </div>
    <div class="location float-left">
       <p> <%= @profile.job %> </p>
      <%= @profile.mystate %>, <%= @profile.mycountry %>
      <p>Age: <%= @profile.age %></p>
      <p><%= @profile.education %></p>
    </div>
    <div class="net_worth show-net_worth float-left">
      <%= image_tag "naira.jpg", class: "naira-logo" %> <%= @profile.net_worth %>
    </div>
    <hr>
    <ul id="source" class="float-left">
      <li><%= @profile.source1 %></li> ||
      <li><%= @profile.source2 %></li> ||
      <li><%= @profile.source3 %></li> 
    </ul>
    <div class="content-container">
      <div class="content">
      <%= @profile.description %>
      </div>
    </div>
  </div>
</div>